-- 카테고리 = '경제', book id, author name, published date 출력, 출판일 기준 ASC
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK B, AUTHOR A
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.CATEGORY LIKE '경제'
ORDER BY B.PUBLISHED_DATE